name: tag releases
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name:
        run: |
          deno task rel:init
          deno task rel:shipit
